# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: scoudert <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/02/11 17:58:37 by scoudert          #+#    #+#              #
#    Updated: 2015/02/20 18:38:59 by scoudert         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

PATH =./SRC/

.PHONY: make fclean clean re

all :
	make -C $(PATH) all

fclean :
	@make -C $(PATH) fclean

clean :
	@make -C $(PATH) clean

re :
	@make -C $(PATH) re
